# Site settings
title: Notes to self
description: Blog of Shekhar Singh a.k.a rootcss | Big Data/Data Engineer | Full Stack Developer | Researcher | Data Science | DevOps | Security | Shekhar Singh

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rootcss.github.io" # the base hostname & protocol for your site

author:
  fullname: Shekhar Singh
  googleplus: ShekharSingh3
  github: rootcss
  twitter: rootcss
  disqus: rootcss
  facebook: rootcss
  linkedin: cshekharsingh
  stackoverflow: users/4908717/rootcss

google_analytics: 'UA-70603998-1'

# Build settings
markdown: kramdown