# top level stuff you probably don't need to touch
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://shekharsingh.com/
baseurl: /
title: Blog of Shekhar Singh a.k.a rootcss | Big Data/Data Engineer | Full Stack Developer | Researcher | Data Science | DevOps | Security | Shekhar Singh
author: Shekhar Singh
description: Blog of Shekhar Singh a.k.a rootcss | Big Data/Data Engineer | Full Stack Developer | Researcher | Data Science | DevOps | Security | Shekhar Singh
avatar: profile.jpg
email: shekhar.singh@msn.com
github: rootcss
twitter: rootcss
linkedin: cshekharsingh
stackoverflow: users/4908717/rootcss
googleplus: ShekharSingh3
facebook: rootcss
disqus: rootcss
google_analytics: UA-70603998-1

# needed for travis-ci build
exclude: [vendor]
