# top level stuff you probably don't need to touch
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: https://shekharsingh.com/
baseurl: /
title: Shekhar Singh - Tech, Data, Fitness, Books - rootcss
author: Shekhar Singh
description: Shekhar Singh - Tech, Data, Fitness, Books | All things Backend. Services, Data, DevOps | Consultant, Freelancer | rootcss
avatar: profile.jpg
email: shekhar [.] singh [@] msn [.] com
github: rootcss
twitter: rootcss
linkedin: cshekharsingh
stackoverflow: users/4908717/rootcss
googleplus: ShekharSingh3
facebook: rootcss
disqus: rootcss
google_analytics: UA-70603998-1

# needed for travis-ci build
exclude: [vendor]
