# top level stuff you probably don't need to touch
highlighter: pygments
markdown: kramdown
# rdiscount:
  # extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://shekharsingh.com/
baseurl: /
title: Shekhar Singh
author: Shekhar Singh
description: Personal blog and resume
avatar: profile.jpg
email: shekhar.singh@msn.com
github: rootcss
twitter: rootcss
linkedin: cshekharsingh
stackoverflow: users/4908717/rootcss
googleplus: ShekharSingh3
facebook: rootcss
disqus: rootcss
google_analytics: UA-70603998-1

# needed for travis-ci build
exclude: [vendor]
